package com.wmq.lecture.mapper;

import com.wmq.lecture.entity.BookLecture;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface BookLectureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_lecture
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    int insert(BookLecture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_lecture
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    List<BookLecture> selectAll();

    List topLecture();
    List topStudent();
    List topSpeaker();
    List<BookLecture> getLectureBookers(String lecNumber);
    int checkSign(@Param("stuNumber") String stuNumber, @Param("lecNumber") String lecNumber);

}