package com.wmq.lecture.mapper;

import com.wmq.lecture.entity.OutDateLecture;
import java.util.List;

public interface OutDateLectureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_date_lecture
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    int insert(OutDateLecture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_date_lecture
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    List<OutDateLecture> selectAll();
}