spring:
  datasource:
    url: jdbc:mysql://47.108.211.133:3306/lecture?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mm232326.
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mybatis/mappers/*Mapper.xml
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8088
  servlet:
    context-path: /api
