package com.wmq.lecture.entity;

import java.sql.Time;
import java.util.Date;

public class BookLecture {
    private String stuNumber;
    private String roomNumber;
    private String lecNumber;
    private Integer rrow;
    private Integer collumn;
    private String time;
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_lecture.score
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    private Double score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_lecture.stu_number
     *
     * @return the value of book_lecture.stu_number
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public String getStuNumber() {
        return stuNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_lecture.stu_number
     *
     * @param stuNumber the value for book_lecture.stu_number
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public void setStuNumber(String stuNumber) {
        this.stuNumber = stuNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_lecture.room_number
     *
     * @return the value of book_lecture.room_number
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public String getRoomNumber() {
        return roomNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_lecture.room_number
     *
     * @param roomNumber the value for book_lecture.room_number
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public void setRoomNumber(String roomNumber) {
        this.roomNumber = roomNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_lecture.lec_number
     *
     * @return the value of book_lecture.lec_number
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public String getLecNumber() {
        return lecNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_lecture.lec_number
     *
     * @param lecNumber the value for book_lecture.lec_number
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public void setLecNumber(String lecNumber) {
        this.lecNumber = lecNumber;
    }
    public Integer getRrow() {
        return rrow;
    }
    public void setRrow(Integer rrow) {
        this.rrow = rrow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_lecture.collumn
     *
     * @return the value of book_lecture.collumn
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public Integer getCollumn() {
        return collumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_lecture.collumn
     *
     * @param collumn the value for book_lecture.collumn
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public void setCollumn(Integer collumn) {
        this.collumn = collumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_lecture.time
     *
     * @return the value of book_lecture.time
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_lecture.time
     *
     * @param time the value for book_lecture.time
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_lecture.date
     *
     * @return the value of book_lecture.date
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_lecture.date
     *
     * @param date the value for book_lecture.date
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_lecture.score
     *
     * @return the value of book_lecture.score
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_lecture.score
     *
     * @param score the value for book_lecture.score
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public void setScore(Double score) {
        this.score = score;
    }
}