package com.wmq.lecture.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.sql.Time;
import java.util.Date;

/**
 * @author lenovo
 */
public class Lecture {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lecture.lec_number
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    private String lecNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lecture.lec_room
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    private String lecRoom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lecture.title
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lecture.speaker
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    private String speaker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lecture.lec_score
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    private Double lecScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lecture.lec_date
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
//    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date lecDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lecture.lec_time
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    private Time lecTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lecture.introduction
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lecture.content
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lecture.lec_number
     *
     * @return the value of lecture.lec_number
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public String getLecNumber() {
        return lecNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lecture.lec_number
     *
     * @param lecNumber the value for lecture.lec_number
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public void setLecNumber(String lecNumber) {
        this.lecNumber = lecNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lecture.lec_room
     *
     * @return the value of lecture.lec_room
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public String getLecRoom() {
        return lecRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lecture.lec_room
     *
     * @param lecRoom the value for lecture.lec_room
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public void setLecRoom(String lecRoom) {
        this.lecRoom = lecRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lecture.title
     *
     * @return the value of lecture.title
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lecture.title
     *
     * @param title the value for lecture.title
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lecture.speaker
     *
     * @return the value of lecture.speaker
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public String getSpeaker() {
        return speaker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lecture.speaker
     *
     * @param speaker the value for lecture.speaker
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public void setSpeaker(String speaker) {
        this.speaker = speaker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lecture.lec_score
     *
     * @return the value of lecture.lec_score
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public Double getLecScore() {
        return lecScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lecture.lec_score
     *
     * @param lecScore the value for lecture.lec_score
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public void setLecScore(Double lecScore) {
        this.lecScore = lecScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lecture.lec_date
     *
     * @return the value of lecture.lec_date
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public Date getLecDate() {
        return lecDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lecture.lec_date
     *
     * @param lecDate the value for lecture.lec_date
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
//    @DateTimeFormat（pattern:yyyy-MM-dd）
    public void setLecDate(Date lecDate) {
        this.lecDate = lecDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lecture.lec_time
     *
     * @return the value of lecture.lec_time
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public Time getLecTime() {
        return lecTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lecture.lec_time
     *
     * @param lecTime the value for lecture.lec_time
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public void setLecTime(Time lecTime) {
        this.lecTime = lecTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lecture.introduction
     *
     * @return the value of lecture.introduction
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lecture.introduction
     *
     * @param introduction the value for lecture.introduction
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lecture.content
     *
     * @return the value of lecture.content
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lecture.content
     *
     * @param content the value for lecture.content
     *
     * @mbg.generated Tue Jan 12 17:56:06 CST 2021
     */
    public void setContent(String content) {
        this.content = content;
    }
}