package com.wmq.lecture.entity;

import java.util.Date;

public class OutDateLecture {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_date_lecture.lec_number
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    private String lecNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_date_lecture.lec_room
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    private String lecRoom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_date_lecture.title
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_date_lecture.speaker
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    private String speaker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_date_lecture.lec_score
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    private Double lecScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_date_lecture.lec_date
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    private Date lecDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_date_lecture.lec_time
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    private String lecTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_date_lecture.introduction
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_date_lecture.content
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_date_lecture.lec_number
     *
     * @return the value of out_date_lecture.lec_number
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    public String getLecNumber() {
        return lecNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_date_lecture.lec_number
     *
     * @param lecNumber the value for out_date_lecture.lec_number
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    public void setLecNumber(String lecNumber) {
        this.lecNumber = lecNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_date_lecture.lec_room
     *
     * @return the value of out_date_lecture.lec_room
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    public String getLecRoom() {
        return lecRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_date_lecture.lec_room
     *
     * @param lecRoom the value for out_date_lecture.lec_room
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    public void setLecRoom(String lecRoom) {
        this.lecRoom = lecRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_date_lecture.title
     *
     * @return the value of out_date_lecture.title
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_date_lecture.title
     *
     * @param title the value for out_date_lecture.title
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_date_lecture.speaker
     *
     * @return the value of out_date_lecture.speaker
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    public String getSpeaker() {
        return speaker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_date_lecture.speaker
     *
     * @param speaker the value for out_date_lecture.speaker
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    public void setSpeaker(String speaker) {
        this.speaker = speaker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_date_lecture.lec_score
     *
     * @return the value of out_date_lecture.lec_score
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    public Double getLecScore() {
        return lecScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_date_lecture.lec_score
     *
     * @param lecScore the value for out_date_lecture.lec_score
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    public void setLecScore(Double lecScore) {
        this.lecScore = lecScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_date_lecture.lec_date
     *
     * @return the value of out_date_lecture.lec_date
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    public Date getLecDate() {
        return lecDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_date_lecture.lec_date
     *
     * @param lecDate the value for out_date_lecture.lec_date
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    public void setLecDate(Date lecDate) {
        this.lecDate = lecDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_date_lecture.lec_time
     *
     * @return the value of out_date_lecture.lec_time
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    public String getLecTime() {
        return lecTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_date_lecture.lec_time
     *
     * @param lecTime the value for out_date_lecture.lec_time
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    public void setLecTime(String lecTime) {
        this.lecTime = lecTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_date_lecture.introduction
     *
     * @return the value of out_date_lecture.introduction
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_date_lecture.introduction
     *
     * @param introduction the value for out_date_lecture.introduction
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_date_lecture.content
     *
     * @return the value of out_date_lecture.content
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_date_lecture.content
     *
     * @param content the value for out_date_lecture.content
     *
     * @mbg.generated Thu Feb 18 11:32:55 CST 2021
     */
    public void setContent(String content) {
        this.content = content;
    }
}